## Answer (a)

Verify the computation of at least two sensitivities of your choice.

$$
S=\begin{pmatrix}
0.3 & 0 & 0 \\
0 & 0.2 & 0 \\
0 & 0 & 0.15 \\
\end{pmatrix}
$$


In [12]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import norm
from scipy.optimize import fsolve

mu = np.array([[0],
               [0],
               [0]])

stdev = np.array([[0.30],
                  [0.20],
                  [0.15]])

w = np.array([[0.5],
              [0.2],
              [0.3]])

relation = np.array([[1.0, 0.8, 0.5],
                     [0.8, 1.0, 0.3],
                     [0.5, 0.3, 1.0]])

In [13]:
S = np.diag(stdev.flatten())
S

array([[0.3 , 0.  , 0.  ],
       [0.  , 0.2 , 0.  ],
       [0.  , 0.  , 0.15]])

Define 
$$\sum=SRS'=SRS=
\begin{pmatrix}
0.0900	& 0.0480	& 0.0225 \\
0.0480	& 0.0400	& 0.0090 \\
0.0225	& 0.0090	& 0.0225 \\
\end{pmatrix}
$$

In [14]:
SRS = S @ relation @ S
SRS

array([[0.09  , 0.048 , 0.0225],
       [0.048 , 0.04  , 0.009 ],
       [0.0225, 0.009 , 0.0225]])


$$\sum\omega=
\begin{pmatrix}
0.0900	& 0.0480	& 0.0225 \\
0.0480	& 0.0400	& 0.0090 \\
0.0225	& 0.0090	& 0.0225 \\
\end{pmatrix}
\begin{pmatrix}
50\% \\
20\% \\
30\% \\
\end{pmatrix}
=\begin{pmatrix}
0.0614 \\
0.0347 \\
0.0198 \\
\end{pmatrix}
$$

In [20]:
sigma_w = SRS @ w
sigma_w

array([[0.06135],
       [0.0347 ],
       [0.0198 ]])

$$
\omega'\sum\omega=
\begin{pmatrix}
50\% \\
20\% \\
30\% \\
\end{pmatrix}'
\begin{pmatrix}
0.0900	& 0.0480	& 0.0225 \\
0.0480	& 0.0400	& 0.0090 \\
0.0225	& 0.0090	& 0.0225 \\
\end{pmatrix}
\begin{pmatrix}
50\% \\
20\% \\
30\% \\
\end{pmatrix}
=0.043555
$$

So,
$$\sqrt{\omega'\sum\omega}=0.2087$$

In [21]:
w_sigma_w = w.T @ sigma_w
w_sigma_w_sqrt = np.sqrt(w_sigma_w)
w_sigma_w_sqrt

array([[0.20869835]])

$$\frac{\partial VaR(\omega)}{\partial \omega_1}=\mu_1+z_\alpha * \frac{(\sum\omega)_1}{\sqrt{\omega'\sum\omega}}=-0.6838$$


$$\frac{\partial VaR(\omega)}{\partial \omega_2}=\mu_2+z_\alpha * \frac{(\sum\omega)_2}{\sqrt{\omega'\sum\omega}}=-0.3867$$


$$\frac{\partial VaR(\omega)}{\partial \omega_3}=\mu_3+z_\alpha * \frac{(\sum\omega)_3}{\sqrt{\omega'\sum\omega}}=-0.2207$$

In [27]:
sensitivity = mu + (-2.326) * sigma_w / w_sigma_w_sqrt
sensitivity
print("Sensitivity of the portfolio at 1% VaR level: ")
print(sensitivity)

sensitivity_1 = sensitivity.flatten()[0]
sensitivity_2 = sensitivity.flatten()[1]
sensitivity_3 = sensitivity.flatten()[2]

print(f"Sensitivity of asset 1: {sensitivity_1:.4f}")
print(f"Sensitivity of asset 2: {sensitivity_2:.4f}")
print(f"Sensitivity of asset 3: {sensitivity_3:.4f}")

Sensitivity of the portfolio at 1% VaR level: 
[[-0.68376248]
 [-0.38674096]
 [-0.2206764 ]]
Sensitivity of asset 1: -0.6838
Sensitivity of asset 2: -0.3867
Sensitivity of asset 3: -0.2207



## Answer (b)
1.
All three assets are positively correlated, so increasing the weight of any asset raises the overall portfolio volatility and tail risk.
In the formula, zα is negative, and the magnitude of the risk term dominates the expected return term, making marginal VaR and marginal ES negative.

2.
Negative sensitivities means increasing the weight of any asset causes the portfolio VaR to become more negative, representing a larger potential loss and higher portfolio risk.

## Answer (c)
Asset 1 has both the highest volatility and the largest weight, leading to the strongest marginal impact on portfolio risk. Hence, it exhibits the most negative sensitivity.

## Answer (d)
#### Mathematical reason:

$$\mu_i=0%$$

So, compare the absolute value of

$$
\lvert z_\alpha \rvert=2.326
$$ 

and

$$|\frac{\phi(z_\alpha)}{1-c}|=|\frac{0.02667}{0.01}|=2.667$$

So

$$\frac{\phi(z_\alpha)}{1-c}>z_\alpha$$


#### Definition reason:
VaR only looks at the quantile level, while ES looks at the average loss in the tail and is more sensitive to tail risk.

Therefore, changes in marginal weights have a larger impact on ES.
